import { Suspense, useMemo, useRef, useState } from 'react'
import { Canvas, ThreeEvent, useFrame } from '@react-three/fiber'
import { ContactShadows, RoundedBox } from '@react-three/drei'
import * as THREE from 'three'
const STEP=1.0
type Axis='x'|'y'|'z'
type Turn={axis:Axis;direction:number;elapsed:number;pieces:THREE.Group[]}
type Theme='dark'|'light'
type PlateProps={axis:Axis;sign:number;variant:number;theme:Theme;onClick:(e:ThreeEvent<MouseEvent>)=>void}
function useDotTexture(theme:Theme){return useMemo(()=>{const c=document.createElement('canvas');c.width=c.height=96;const x=c.getContext('2d')!,light=theme==='light';x.fillStyle=light?'#4f83ad':'#17181a';x.fillRect(0,0,96,96);x.fillStyle=light?'rgba(230,247,255,.38)':'rgba(210,210,210,.28)';for(let a=4;a<96;a+=8)for(let b=4;b<96;b+=8){x.beginPath();x.arc(a,b,light?1.5:1.25,0,Math.PI*2);x.fill()}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;return t},[theme])}
function FacePlate({axis,sign,variant,theme,onClick}:PlateProps){
 const dots=useDotTexture(theme),light=theme==='light'
 const position:[number,number,number]=axis==='x'?[sign*.497,0,0]:axis==='y'?[0,sign*.497,0]:[0,0,sign*.497]
 const rotation:[number,number,number]=axis==='x'?[0,Math.PI/2,0]:axis==='y'?[Math.PI/2,0,0]:[0,0,0]
 const dotted=variant===0,matte=variant===1,mirror=variant===2
 const color=light?(dotted?'#4f83ad':matte?'#6d9fc7':mirror?'#b9d8ed':'#7fb3da'):(dotted?'#333538':matte?'#3b3d40':mirror?'#4b4d50':'#292b2e')
 return <RoundedBox args={[.958,.958,.034]} radius={.055} smoothness={5} position={position} rotation={rotation} onClick={onClick}><meshPhysicalMaterial map={dotted?dots:null} color={color} metalness={light?(mirror?.62:dotted?.16:.28):(dotted?.12:matte?.16:mirror?.68:.42)} roughness={light?(dotted?.54:matte?.68:mirror?.1:.32):(dotted?.62:matte?.7:mirror?.08:.2)} clearcoat={light?(matte?.18:.72):(matte?.12:1)} clearcoatRoughness={light?(matte?.6:.16):(matte?.72:.06)} sheen={light?.32:0} sheenColor={light?'#d9efff':'#000000'}/></RoundedBox>
}
function Core({intro=false,theme='dark'}:{intro?:boolean;theme?:Theme}){
 const display=useRef<THREE.Group>(null),root=useRef<THREE.Group>(null),pivot=useRef<THREE.Group>(null),pieces=useRef<(THREE.Group|null)[]>([]),turn=useRef<Turn|null>(null)
 const [dragging,setDragging]=useState(false),drag=useRef({x:0,y:0,moved:false}),rotation=useRef({x:-.5,y:.62}),autoStep=useRef(0),lastAuto=useRef(2.2)
 const cells=useMemo(()=>{const a:{p:[number,number,number],grid:[number,number,number]}[]=[];for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++)a.push({p:[x*STEP,y*STEP,z*STEP],grid:[x,y,z]});return a},[])
 useFrame((state,delta)=>{if(display.current&&!dragging){const time=state.clock.elapsedTime;const targetX=rotation.current.x+Math.sin(time*.76)*.14+Math.cos(time*.33)*.055+state.pointer.y*.085;const targetY=rotation.current.y+Math.sin(time*.58)*.3+Math.cos(time*.28)*.11+state.pointer.x*.12;const targetZ=Math.sin(time*.69)*.055+Math.cos(time*.39)*.018;display.current.rotation.x=THREE.MathUtils.damp(display.current.rotation.x,targetX,5.5,delta);display.current.rotation.y=THREE.MathUtils.damp(display.current.rotation.y,targetY,5.5,delta);display.current.rotation.z=THREE.MathUtils.damp(display.current.rotation.z,targetZ,4.5,delta)}if(!intro&&!turn.current&&!dragging&&pivot.current&&state.clock.elapsedTime-lastAuto.current>2.15){const sequence:{axis:Axis,level:number,direction:number}[]=[{axis:'y',level:1,direction:1},{axis:'x',level:-1,direction:-1},{axis:'z',level:1,direction:1},{axis:'y',level:0,direction:-1},{axis:'x',level:1,direction:1},{axis:'z',level:-1,direction:-1}],next=sequence[autoStep.current%sequence.length],selected=pieces.current.filter((p):p is THREE.Group=>Boolean(p&&Math.round(p.position[next.axis]/STEP)===next.level));selected.forEach(p=>pivot.current!.attach(p));turn.current={axis:next.axis,direction:next.direction,elapsed:0,pieces:selected};autoStep.current++;lastAuto.current=state.clock.elapsedTime}const a=turn.current;if(!a||!pivot.current||!root.current)return;a.elapsed+=delta;const t=Math.min(a.elapsed/.4,1),e=t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;pivot.current.rotation[a.axis]=a.direction*Math.PI/2*e;if(t===1){a.pieces.forEach(p=>{root.current!.attach(p);p.position.set(Math.round(p.position.x/STEP)*STEP,Math.round(p.position.y/STEP)*STEP,Math.round(p.position.z/STEP)*STEP);const q=new THREE.Euler().setFromQuaternion(p.quaternion,'XYZ');q.set(...([q.x,q.y,q.z].map(v=>Math.round(v/(Math.PI/2))*Math.PI/2) as [number,number,number]));p.quaternion.setFromEuler(q)});pivot.current.rotation.set(0,0,0);turn.current=null}})
 const layer=(event:ThreeEvent<MouseEvent>,piece:THREE.Group,forcedAxis?:Axis,forcedSign=1)=>{event.stopPropagation();if(turn.current||drag.current.moved||!pivot.current)return;let axis=forcedAxis,faceDirection=forcedSign;if(!axis&&event.face){const normal=event.face.normal.clone().applyQuaternion(piece.quaternion),v={x:Math.abs(normal.x),y:Math.abs(normal.y),z:Math.abs(normal.z)};axis=(Object.keys(v) as Axis[]).reduce((a,b)=>v[a]>v[b]?a:b);faceDirection=Math.sign(normal[axis])||1}if(!axis)return;const level=Math.round(piece.position[axis]/STEP),selected=pieces.current.filter((p):p is THREE.Group=>Boolean(p&&Math.round(p.position[axis]/STEP)===level));selected.forEach(p=>pivot.current!.attach(p));turn.current={axis,direction:(event.nativeEvent.shiftKey?-1:1)*faceDirection,elapsed:0,pieces:selected}}
 return <group ref={display} rotation={[-.5,.62,-.06]} scale={.92} onPointerDown={e=>{setDragging(true);drag.current={x:e.clientX,y:e.clientY,moved:false};(e.target as HTMLElement).setPointerCapture?.(e.pointerId)}} onPointerMove={e=>{if(!dragging||turn.current)return;const dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y;if(Math.abs(dx)+Math.abs(dy)>2)drag.current.moved=true;rotation.current.y+=dx*.006;rotation.current.x+=dy*.006;drag.current.x=e.clientX;drag.current.y=e.clientY}} onPointerUp={()=>setDragging(false)} onPointerLeave={()=>setDragging(false)}><group ref={root}>{cells.map(({p,grid:[x,y,z]},i)=><group key={i} position={p} ref={el=>{pieces.current[i]=el}}><RoundedBox args={[.972,.972,.972]} radius={.085} smoothness={5} onClick={e=>layer(e,pieces.current[i]!)}><meshPhysicalMaterial color={theme==='light'?'#173b57':'#111214'} metalness={theme==='light'?.48:.38} roughness={theme==='light'?.42:.26} clearcoat={theme==='light'?.55:1} clearcoatRoughness={theme==='light'?.22:.08}/></RoundedBox>{x!==0&&<FacePlate axis="x" sign={x} variant={(i+x+6)%4} theme={theme} onClick={e=>layer(e,pieces.current[i]!,'x',x)}/>} {y!==0&&<FacePlate axis="y" sign={y} variant={(i+y+8)%4} theme={theme} onClick={e=>layer(e,pieces.current[i]!,'y',y)}/>} {z!==0&&<FacePlate axis="z" sign={z} variant={(i+z+10)%4} theme={theme} onClick={e=>layer(e,pieces.current[i]!,'z',z)}/>}</group>)}</group><group ref={pivot}/></group>
}
export default function InteractiveCube({intro=false,theme='dark'}:{intro?:boolean;theme?:Theme}){
 const light=theme==='light'
 return <div className={`interactive-cube${intro?" intro-interactive-cube":""}`} aria-label="可交互三阶魔方：拖动整体，点击方块转动对应层，按住 Shift 点击可反向转动"><Canvas dpr={[1,intro?1.25:1.7]} camera={{position:[0,.2,7.8],fov:38}} gl={{antialias:true,alpha:true,powerPreference:'high-performance'}} onCreated={({gl})=>{gl.toneMapping=THREE.ACESFilmicToneMapping;gl.toneMappingExposure=light?.92:1.42}}><ambientLight intensity={light?.42:.7}/><hemisphereLight args={[light?"#e6f7ff":"#e2e2e2",light?"#173b57":"#090909",light?.68:.88]}/><spotLight position={[-5,7,5]} intensity={light?76:155} angle={.3} penumbra={.82} color={light?"#f5fbff":"#fff"}/><rectAreaLight position={[4,2,5]} width={4} height={6} intensity={light?17:28} color={light?"#89c2ff":"#d8d8d8"}/><pointLight position={[-3,-2,4]} intensity={light?11:24} color={light?"#285b82":"#8e8e8e"}/><Suspense fallback={null}><Core intro={intro} theme={theme}/><ContactShadows position={[0,-2.05,0]} opacity={light?.34:.62} scale={8} blur={2.5} far={5}/></Suspense></Canvas>{!intro&&<p>DRAG TO ORBIT · CLICK TO TURN A LAYER<br/><span>SHIFT + CLICK · REVERSE</span></p>}</div>
}